//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int id_cart { get; set; }
        public int id_puzzle { get; set; }
        public int amount { get; set; }
        public string in_usercart { get; set; }
        public Nullable<int> id_purchase { get; set; }
    
        public virtual Puzzle Puzzle { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
