//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puzzle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puzzle()
        {
            this.Cart = new HashSet<Cart>();
        }
    
        public int id_puzzle { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int id_difficulty { get; set; }
        public int id_company { get; set; }
        public int amount { get; set; }
        public int cost { get; set; }
        public int id_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual Company_List Company_List { get; set; }
        public virtual Difficulty Difficulty { get; set; }
        public virtual Types Types { get; set; }
    }
}
